version: 1
update_configs:
  # Keep package.json (& lockfiles) secure and up-to-date,
  # batching pull requests daily
  - package_manager: "terraform"
    directory: "dev/eks/"
    update_schedule: "daily"
